const fs = require('fs');
const path = require('path');

const resourcesDir = path.join(__dirname, '..', 'resources');
const outputDir = path.join(__dirname, '..', 'src', 'js');

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

const outputFile = path.join(outputDir, 'manuals_data.js');
const manuals = [];

// Helper to chunk text by subtitles/numbers
function parseIntoSubtitles(content) {
    const lines = content.split('\n');
    const sections = [];
    let currentSection = { title: "개요", body: [] };

    const subtitleRegex = /^(\d+\.|\[.*?\]|-|\*)\s*(.*)/;

    lines.forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) return;

        // Any line starting with "1.", "[제목]", "-", etc., acts as a new subtitle if it's short.
        const match = trimmed.match(subtitleRegex);
        if (match || (trimmed.endsWith(':') && trimmed.length < 30)) {
            // Push previous section if it has body
            if (currentSection.body.length > 0) {
                sections.push({
                    subtitle: currentSection.title,
                    content: currentSection.body.join('\n')
                });
            }
            currentSection = { title: trimmed, body: [] };
        } else {
            currentSection.body.push(trimmed);
        }
    });

    if (currentSection.body.length > 0) {
        sections.push({
            subtitle: currentSection.title,
            content: currentSection.body.join('\n')
        });
    }

    return sections;
}

try {
    const files = fs.readdirSync(resourcesDir);
    
    files.forEach(file => {
        if (file.endsWith('.txt')) {
            const title = file.replace('.txt', '');
            const filePath = path.join(resourcesDir, file);
            const content = fs.readFileSync(filePath, 'utf-8');
            
            if (content.trim().length > 10) { // skip empty files
                const parsedSections = parseIntoSubtitles(content);
                manuals.push({
                    id: title.replace(/\s+/g, '_'),
                    title: title,
                    sections: parsedSections
                });
            }
        }
    });

    // Write to a JS file so browser can load it immediately without fetch/CORS blocks
    const jsContent = `// Auto-generated by execution/parse_manuals.js
const MANUALS_DATABASE = ${JSON.stringify(manuals, null, 2)};
window.MANUALS_DATABASE = MANUALS_DATABASE;
`;

    fs.writeFileSync(outputFile, jsContent, 'utf-8');
    console.log(`Successfully parsed ${manuals.length} manuals into ${outputFile}`);
    
} catch (error) {
    console.error("Error parsing manuals:", error);
}
